### ISSUE TITLE
docstring for computeOnsOffs.m is totally wrong

### ISSUE THREAD

**Issue by qliu-Inscopix** [sg-s/srinivas.gs_mtools#112]
Shouldn't x(x>0) = 1 be "x(x>0.5) = 1"?

**Comment by sg-s** [comment]
no, because x is assumed to be binary (logical)

**Comment by qliu-Inscopix** [comment]
missing threshold argument in the function body:

veclib.computeOnsOffs([-10,-9,-8,-7,-6,-5,-4,-3,-2,-1,0]) will return [];

veclib.computeOnsOffs([-10,-9,-8,-7,-6,-5,-4,-3,-2,-1,0], -5) gives the "Too many input arguments." error:

**Comment by sg-s** [comment]
```
veclib.computeOnsOffs([-10,-9,-8,-7,-6,-5,-4,-3,-2,-1,0]) will return [];
```

yes, because this is a monotonic sequence -- there are no ons or offs

```
veclib.computeOnsOffs([-10,-9,-8,-7,-6,-5,-4,-3,-2,-1,0], -5)
```

yes, because it only takes one argument -- a (logical) vector. 

what you want to do is:

```
veclib.computeOnsOffs([-10,-9,-8,-7,-6,-5,-4,-3,-2,-1,0] > -5)
```

**Comment by qliu-Inscopix** [comment]
OK, a simple update to the help doc should avoid using a second argument

**Comment by sg-s** [comment]
ah i see the docstring is totally wrong. my bad!

**Comment by sg-s** [comment]
@qliu-Inscopix FYI you will find the docstrings generally unreliable -- ping me if you find something missing/out of sync

**Comment by qliu-Inscopix** [comment]
Will do!
