### ISSUE TITLE
Warnings run running xolotl.run_all_tests

### ISSUE THREAD

**Issue by smbaca** [sg-s/srinivas.gs_mtools#114]
If one replaces this line which throws a warning multiple times when running xolotl.run_all_tests
this_line(strfind(this_line, '%'):end) = [];

With the code below, then the warnings go away.

% Find the index of the first occurrence of '%'
idx = strfind(this_line, '%');

% Check if '%' was found
if ~isempty(idx)
    % Remove everything from the first '%' to the end
    this_line(idx(1):end) = [];
end

**Comment by smbaca** [comment]
Attached is the Mex compiled md5hash file that is required to run xolotl on the new M3 Macs. For whatever reason I could not generate a pull request but hopefully the zipped file gets through

[md5hash.mexa64.zip](https://github.com/user-attachments/files/16013739/md5hash.mexa64.zip)

**Comment by sg-s** [comment]
@smbaca thank you! 

do you want me to help you make a PR, or do you want me to simply add it?

if the former, to make a pull request, you need to fork this repo, make changes, and then press the "make a pull request button" on your version of the code

**Comment by smbaca** [comment]
Feel free to add it. I did not fork the repo so that is probably why I could not do the pull request. (still rather new to Github or rather just sporadic use!)

**Comment by smbaca** [comment]
[Archive.zip](https://github.com/user-attachments/files/16014175/Archive.zip)
Also realizing that there were two files and not sure I sent both of them. In the archive is md5hash.mexa64 and md5hash.mexmaca64

**Comment by sg-s** [comment]
`md5hash.mexa64` is for linux, see https://www.mathworks.com/help/matlab/ref/mexext.html

**Comment by sg-s** [comment]
we don't need that one, just the mexmaca64 (which is the ARM-compiled binary)

**Comment by smbaca** [comment]
Ahhh, too early in the morning. Thanks for the clarification!

__
Serapio M. Baca
***@***.***

**Comment by sg-s** [comment]
fixed. let me know if it's still broken
