### ISSUE TITLE
readPref is not robust

### ISSUE THREAD

**Issue by cellocgw** [sg-s/srinivas.gs_mtools#42]
the called func readPref.m is not robust. It should not expect a prefs file to exist in the same location as the main function; further if it can't find a prefs file it should create an empty or a default set of parameters.

**Comment by sg-s** [comment]
you can specify where the `pref.m` file should be using:

```
readPref('link/to/pref.m')
```

also, if it can't find it, it automatically copies `default.m` into `pref.m` and uses that. 

so you should use a file called `default.m` to define your default set of parameters.
