### ISSUE TITLE
matlab-tools: a function to find which properties of an object are empty

### ISSUE THREAD

**Issue by alec-hoyland** [sg-s/srinivas.gs_mtools#70]
`findData` works for vectors of `struct`s, but what if you are writing a method of a class and you want to check if certain properties are defined first? You could do it by checking each individually, and usually that works, but what about procedurally checking each property of an object? Something like:

```matlab
function bool = isempty(var)

if ~isobject(var)
  bool = isempty(var);
else
  f = properties(var);
  bool = false(length(f), 1);
  for ii = 1:length(f)
    bool(ii) = isempty(var.(f{ii});
  end
end
```

Presumably, you'd want the indices and the name of the field/property.

**Comment by sg-s** [comment]
sure, send me a PR

**Comment by sg-s** [comment]
not what you asked for, but look at this:

https://github.com/sg-s/srinivas.gs_mtools/blob/master/ConstructableHandle.m

**Comment by alec-hoyland** [comment]
This is sorcery

**Comment by sg-s** [comment]
you could write an abstract class like this which would define a method "isempty" that you could apply to any object that inherits from this

**Comment by sg-s** [comment]
This is easily solved with a small code snippet. Let a xolotl object stand in for some arbitrary object. Then what you want is this:

```
p = properties(x); cellfun(@(y) isempty(x.(y)), p)
```
