### ISSUE TITLE
Use xelatex not pdflatex to get around unicode problems while publishing

### ISSUE THREAD

**Issue by alec-hoyland** [sg-s/srinivas.gs_mtools#80]
Here's the problem: latex doesn't do unicode. Specifically, the pdflatex engine doesn't do unicode. You can trick it on a case by case basis, by using \DeclareUnicodeCharacter{}{} to replace one pattern with another, but this doesn't seem to work inside of verbatim blocks, which Mathworks, in their infinite wisdom, have decided is the best way to represent their output.

I imagine part of the reason that this hasn't been fixed is that they've been really pushing their .mlx live scripts (which are egregiously slow, and don't work on GNU/Linux machines if not also macs).

The only solution I have found is to not use pdflatex. If you use xelatex instead, which is unicode-compatible, you don't have this problem. So, the actual solution is to change the pdflatex command (line 122 of pdflib.make) to use xelatex instead.

Since xelatex is bundled with TeX Live, MacTeX, MiKTeX, and Lyx, there shouldn't be a problem with the toolchain.

**Comment by alec-hoyland** [comment]
See PR #81 and input encoding woes [here](https://github.com/sg-s/awesome-matlab-notebook/issues/2)

**Comment by sg-s** [comment]
closing as I assume your PR fixes this
