### ISSUE TITLE
Best practice for hashing non-concrete data

### ISSUE THREAD

**Issue by alec-hoyland** [sg-s/srinivas.gs_mtools#92]
I am looking for the best way to hash nonstandard data, such as that in cells and structs.

For example, I am looking for something that can hash

```matlab
a = {343667, 'aferg', "wgerg", xolotl}
```

Generally, this doesn't work, since:

```matlab
>> hashlib.md5hash(a)
Error using md5hash
*** md5[mex]: Binary mode requires: non-sparse, real, numeric or CHAR data.
```

I see the `Hashable` abstract class, but I genuinely do not understand how to use it. I also see the `GetMD5_helper` function, but that doesn't seem to work as I expect it either:

```matlab
>> hashlib.hash(hashlib.GetMD5_helper(a))
### Conversion to uint8 from cell is not possible.: Convert object to struct as fallback.
    Error using struct
Conversion to struct from cell is not possible.

Error in hashlib.GetMD5_helper (line 86)
      S     = struct(V);
```

**Comment by sg-s** [comment]
To hash that hetergenous cell array, you'll have to hash each thing individually, and then hash the hashes. 

If you want to write a class that is hashable, it should inherit from `Hashable`

```
classdef YourClass < Hashable
```

and that's it. Your class will have a method called hash
